"""Remove form_type from FormData

Revision ID: 01b86f3d03b8
Revises: 1d312265f023
Create Date: 2024-08-03 23:18:14.954029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b86f3d03b8'
down_revision = '1d312265f023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.drop_column('form_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
